In [39]:
import joblib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import categories4
pd.set_option('display.min_rows', 50)
pd.set_option('display.max_columns', 500)
pd.set_option('max_colwidth', None)

Welcome to JupyROOT 6.28/00

In [40]:
def mygroupby(d, groupbycols):
    g = d.groupby(groupbycols).size().reset_index(name='count').sort_values([ 'count'], ascending=False).reset_index(drop=True)
    g["Percentage"] = g.apply(lambda row: 100 * row["count"]/d.shape[0], axis=1)
    g["cumulative %"] = g["Percentage"].cumsum(axis = 0)
    return g

In [41]:
def load_data(categ):
    df = joblib.load(f"../rds_categdecays_{categ}_2012_23903000_magdown_rs.pkl")
    dfd = df.query("Xc_Selection == 1 & B_Y_SEP < -4.5 & q2_2>0 & BDT_Iso > 0.03458 & B_MM < 5000")
    return dfd

In [45]:
print(f"Categorie 14: {categories4.categories_map[14]}")
df = load_data(14)
g = mygroupby(df[['decay']], 'decay')
g

Categorie 14: Xc_signal_Ypis_diffVertex_doubleCharm_OneFromB

,decay,count,Percentage,cumulative %
0,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> pi- pi+ ] ],512,3.570432,3.570432
1,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> [ D0 -> pi+ pi- ] pi+ ],492,3.430962,7.001395
2,[ ( b~ -> B*0 -> B0 -> D*(2010)- ) -> [ D~0 -> pi- pi+ ] pi- ],467,3.256625,10.258020
3,[ ( b~ -> B*0 -> B0 -> D*(2010)- ) -> pi- [ D~0 -> pi+ pi- ] ],420,2.928870,13.186890
4,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> pi- [ D~0 -> pi+ pi- ] ],245,1.708508,14.895397
5,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ D~0 -> pi- pi+ ] pi- ],221,1.541144,16.436541
6,[ ( b~ -> B*0 -> B0 -> D*(2010)+ ) -> [ D0 -> pi+ pi- ] pi+ ],209,1.457462,17.894003
7,[ ( b~ -> B*0 -> B0 -> D*(2010)+ ) -> pi+ [ D0 -> pi- pi+ ] ],192,1.338912,19.232915
8,[ ( b -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> pi- pi+ ] ],181,1.262204,20.495119
9,[ ( b~ -> B0 -> D*(2010)- ) -> pi- [ D~0 -> pi+ pi- ] ],168,1.171548,21.666667
10,[ ( b -> B~0 -> D*(2010)+ ) -> [ D0 -> pi+ pi- ] pi+ ],162,1.129707,22.796374
11,[ ( b~ -> B0 -> D*(2010)- ) -> [ D~0 -> pi- pi+ ] pi- ],160,1.115760,23.912134
12,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> ( K*(892)- -> pi- ) ( rho(770)+ -> pi+ ) ] ],122,0.850767,24.762901
13,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> [ D0 -> ( rho(770)+ -> pi+ ) ( K*(892)- -> pi- ) ] pi+ ],107,0.746165,25.509066
14,[ ( b~ -> B*0 -> B0 -> D*(2010)- ) -> pi- [ D~0 -> ( K*(892)+ -> pi+ ) ( rho(770)- -> pi- ) ] ],106,0.739191,26.248257
15,[ ( b~ -> B*0 -> B0 -> D*(2010)- ) -> [ D~0 -> ( rho(770)- -> pi- ) ( K*(892)+ -> pi+ ) ] pi- ],88,0.613668,26.861925
16,[ ( b~ -> B0 -> D*(2010)+ ) -> pi+ [ D0 -> pi- pi+ ] ],80,0.557880,27.419805
17,[ ( b -> B~0 -> D*(2010)- ) -> pi- [ D~0 -> pi+ pi- ] ],77,0.536960,27.956764
18,[ ( b -> B~0 -> D*(2010)- ) -> [ D~0 -> pi- pi+ ] pi- ],63,0.439331,28.396095
19,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> [ ( D0 -> omega(782) ) -> pi+ pi- ] pi+ ],63,0.439331,28.835425
20,[ ( b~ -> B0 -> D*(2010)+ ) -> [ D0 -> pi+ pi- ] pi+ ],62,0.432357,29.267782
21,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ ( D0 -> omega(782) ) -> pi- pi+ ] ],58,0.404463,29.672245
22,[ ( b -> B(s)*~0 -> B(s)~0 -> D*(2010)- ) -> pi- [ D~0 -> pi+ pi- ] ],57,0.397490,30.069735
23,[ ( b -> B*- -> B- ) -> ( D+ -> pi+ ) pi- ( D+ -> pi+ ) ],57,0.397490,30.467225
24,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ D~0 -> ( rho(770)- -> pi- ) ( K*(892)+ -> pi+ ) ] pi- ],54,0.376569,30.843794
...,...,...,...,...
3940,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ D~0 -> mu- ( rho(770)+ -> pi+ ) ] pi- ],1,0.006974,99.832636
3941,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> ( K(1)(1270)- -> rho(770)- -> pi- ) e+ ] ],1,0.006974,99.839609
3942,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ D~0 -> e- ( K*(892)+ -> pi+ ) ] ( pi- -> mu- ) ],1,0.006974,99.846583
3943,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> ( K(2)*(1430)- -> K*(892)- -> pi- ) mu+ ] ],1,0.006974,99.853556
3944,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> ( K(2)*(1430)- -> pi- ) e+ ] ],1,0.006974,99.860530
3945,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> ( eta -> pi- ) pi+ ] ],1,0.006974,99.867503
3946,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> ( eta'(958) -> omega(782) -> pi- ) ( K*(892)~0 -> pi+ ) ] ],1,0.006974,99.874477
3947,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> ( eta'(958) -> rho(770)0 -> pi- ) pi+ ] ],1,0.006974,99.881450
3948,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> ( pi0 -> gamma -> e- ) pi+ ] ],1,0.006974,99.888424
3949,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> ( rho(770)- -> pi- ) ( pi+ -> mu+ ) ] ],1,0.006974,99.895397
3950,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> pi- ( K*(892)+ -> pi+ ) ] ],1,0.006974,99.902371
3951,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> pi- ( omega(782) -> pi+ ) ] ],1,0.006974,99.909344
3952,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> pi- ( pi+ -> mu+ ) ] ],1,0.006974,99.916318
3953,[ ( b -> B*~0 -> B~0 -> D*(2010)+ ) -> pi+ [ D0 -> pi- ( rho(770)+ -> pi0 -> gamma -> e+ ) ] ],1,0.006974,99.923291
3954,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> ( D~0 -> pi+ ) pi- ( D~0 -> pi+ ) ],1,0.006974,99.930265
3955,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> ( pi0 -> gamma -> e- ) [ D- -> pi+ pi- ] ],1,0.006974,99.937238
3956,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ ( D~0 -> K(1)(1270)+ ) -> ( K*(892)0 -> pi- ) pi+ ] pi- ],1,0.006974,99.944212
3957,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ ( D~0 -> K(1)(1270)0 ) -> pi- ( K*(892)+ -> pi+ ) ] pi- ],1,0.006974,99.951185
3958,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ ( D~0 -> eta'(958) -> omega(782) ) -> pi- pi+ ] pi- ],1,0.006974,99.958159
3959,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ ( D~0 -> phi(1020) ) -> ( rho(770)- -> pi- -> mu- ) pi+ ] pi- ],1,0.006974,99.965132
3960,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ ( D~0 -> pi0 -> gamma ) -> e- e+ ] pi- ],1,0.006974,99.972106
3961,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ ( D~0 -> rho(770)- ) -> pi- ( pi0 -> gamma -> e+ ) ] pi- ],1,0.006974,99.979079
3962,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ D~0 -> ( omega(782) -> pi- ) pi+ ] pi- ],1,0.006974,99.986053
3963,[ ( b -> B*~0 -> B~0 -> D*(2010)- ) -> [ D~0 -> ( rho(770)0 -> pi- ) ( rho(770)0 -> pi+ ) ] pi- ],1,0.006974,99.993026
3964,[ b~ -> [ B0 -> ( D~0 -> pi- ) ( D~0 -> pi+ ) ] ( B0 -> pi- ) ],1,0.006974,100.000000

In [46]:
print(f"Categorie 15: {categories4.categories_map[15]}")
df = load_data(15)
g = mygroupby(df[['decay']], 'decay')
g

Categorie 15: Xc_signal_Ypis_diffVertex_doubleCharm_TwoFromB

,decay,count,Percentage,cumulative %
0,[ ( b -> B*- -> B- ) -> pi+ pi- ( D0 -> pi+ ) ],12,2.439024,2.439024
1,[ ( b -> B*~0 -> B~0 ) -> ( D+ -> pi+ ) pi- pi+ ],11,2.235772,4.674797
2,[ ( b -> B*~0 -> B~0 ) -> pi+ pi- ( D+ -> pi+ ) ],10,2.032520,6.707317
3,[ ( b~ -> B*+ -> B+ ) -> pi- pi+ ( D~0 -> pi- ) ],9,1.829268,8.536585
4,[ ( b~ -> B*0 -> B0 ) -> ( D- -> pi- ) pi+ pi- ],9,1.829268,10.365854
5,[ ( b -> B*- -> B- ) -> ( D0 -> pi+ ) pi- pi+ ],8,1.626016,11.991870
6,[ ( b -> B*~0 -> B~0 ) -> pi+ pi- ( D+ -> mu+ ) ],8,1.626016,13.617886
7,[ ( b~ -> B*0 -> B0 ) -> ( D- -> mu- ) pi+ pi- ],7,1.422764,15.040650
8,[ ( b~ -> B*0 -> B0 ) -> pi- pi+ ( D- -> pi- ) ],7,1.422764,16.463415
9,[ ( b -> B- ) -> ( D0 -> pi+ ) pi- pi+ ],6,1.219512,17.682927
10,[ ( b~ -> B*0 -> B0 ) -> pi- pi+ ( D- -> mu- ) ],6,1.219512,18.902439
11,[ ( b~ -> B*+ -> B+ ) -> ( D~0 -> pi- ) pi+ pi- ],6,1.219512,20.121951
12,[ ( b~ -> B*0 -> B0 ) -> ( D+ -> pi+ ) pi- pi+ ],6,1.219512,21.341463
13,[ ( b -> B*~0 -> B~0 ) -> ( D+ -> mu+ ) pi- pi+ ],6,1.219512,22.560976
14,[ ( b~ -> B*+ -> B+ -> D(2)*(2460)~0 ) -> ( D*(2010)- -> D~0 -> pi- ) pi+ ( D*(2010)- -> pi- ) ],5,1.016260,23.577236
15,[ ( b -> B*- -> B- ) -> pi+ pi- ( D0 -> rho(770)+ -> pi+ ) ],5,1.016260,24.593496
16,[ ( b~ -> B*0 -> B0 ) -> pi+ pi- ( D+ -> pi+ ) ],5,1.016260,25.609756
17,[ ( b~ -> B+ ) -> pi- pi+ ( D~0 -> pi- ) ],5,1.016260,26.626016
18,[ ( b -> B*- -> B- -> D(2)*(2460)0 ) -> ( D*(2010)+ -> pi+ ) pi- ( D*(2010)+ -> D0 -> pi+ ) ],5,1.016260,27.642276
19,[ ( b -> B*- -> B- -> D(1)(2420)0 ) -> ( D*(2010)+ -> D0 -> pi+ ) pi- ( D*(2010)+ -> pi+ ) ],4,0.813008,28.455285
20,[ ( b -> B*- -> B- -> D(1)(2430)0 ) -> ( D*(2010)+ -> D0 -> pi+ ) pi- ( D*(2010)+ -> pi+ ) ],4,0.813008,29.268293
21,[ ( b~ -> B*+ -> B+ -> D(1)(2420)~0 ) -> ( D*(2010)- -> pi- ) pi+ ( D*(2010)- -> D~0 -> pi- ) ],4,0.813008,30.081301
22,[ ( b -> B*~0 -> B~0 ) -> ( D- -> pi- ) pi+ pi- ],4,0.813008,30.894309
23,[ ( b -> B- -> D(2)*(2460)0 ) -> ( D*(2010)+ -> pi+ ) pi- ( D*(2010)+ -> D0 -> pi+ ) ],4,0.813008,31.707317
24,[ ( b~ -> B+ ) -> ( D~0 -> pi- ) pi+ pi- ],3,0.609756,32.317073
...,...,...,...,...
278,[ ( b -> B*~0 -> B~0 ) -> ( D(s)*- -> gamma -> e+ ) pi- ( D+ -> mu+ ) ],1,0.203252,95.121951
279,[ ( b -> B*~0 -> B~0 ) -> ( D(s0)*(2317)+ -> pi0 -> gamma -> e- ) [ D*(2010)- -> ( D~0 -> eta -> pi+ ) pi- ] ],1,0.203252,95.325203
280,[ ( b -> B*~0 -> B~0 ) -> ( D*(2010)+ -> D+ -> K*(892)~0 -> pi+ ) [ eta -> pi- pi+ ] ],1,0.203252,95.528455
281,[ ( b -> B*~0 -> B~0 ) -> ( D*(2010)+ -> D+ -> pi+ ) pi- pi+ ],1,0.203252,95.731707
282,[ ( b -> B*~0 -> B~0 ) -> ( D*(2010)+ -> D0 -> pi+ ) ( eta -> pi- ) ( D*(2010)+ -> pi+ ) ],1,0.203252,95.934959
283,[ ( b -> B*~0 -> B~0 ) -> ( D*(2010)- -> D~0 -> pi- ) ( eta'(958) -> rho(770)0 -> pi+ ) ( D*(2010)- -> pi- ) ],1,0.203252,96.138211
284,[ ( b -> B*~0 -> B~0 ) -> ( D+ -> a(1)(1260)+ -> pi+ ) pi- pi+ ],1,0.203252,96.341463
285,[ ( b -> B*~0 -> B~0 ) -> ( D+ -> eta'(958) -> pi+ ) pi- pi+ ],1,0.203252,96.544715
286,[ ( b -> B*~0 -> B~0 ) -> ( D+ -> mu+ ) pi- ( rho(770)+ -> pi+ ) ],1,0.203252,96.747967
287,[ ( b -> B*~0 -> B~0 ) -> ( D+ -> pi+ ) [ eta'(958) -> pi- pi+ ] ],1,0.203252,96.951220
288,[ ( b -> B*~0 -> B~0 ) -> ( D+ -> pi+ ) pi- ( rho(770)+ -> pi+ ) ],1,0.203252,97.154472
289,[ ( b -> B*~0 -> B~0 ) -> ( D+ -> rho(770)+ -> pi+ ) pi- pi+ ],1,0.203252,97.357724
290,[ ( b -> B*~0 -> B~0 ) -> ( D- -> e- ) pi+ pi- ],1,0.203252,97.560976
291,[ ( b -> B*~0 -> B~0 ) -> ( D- -> mu- ) [ omega(782) -> pi+ pi- ] ],1,0.203252,97.764228
292,[ ( b -> B*~0 -> B~0 ) -> ( D- -> mu- ) pi+ pi- ],1,0.203252,97.967480
293,[ ( b -> B*~0 -> B~0 ) -> ( D- -> pi- ) [ omega(782) -> pi+ pi- ] ],1,0.203252,98.170732
294,[ ( b -> B*~0 -> B~0 ) -> ( D- -> rho(770)0 -> pi- ) pi+ pi- ],1,0.203252,98.373984
295,[ ( b -> B*~0 -> B~0 ) -> [ eta -> pi+ pi- ] ( D*(2010)+ -> D+ -> mu+ ) ],1,0.203252,98.577236
296,[ ( b -> B*~0 -> B~0 ) -> [ rho(770)0 -> pi+ pi- ] ( D(s)+ -> omega(782) -> pi+ ) ],1,0.203252,98.780488
297,[ ( b -> B*~0 -> B~0 ) -> pi+ pi- ( D(s)+ -> K*(892)+ -> pi+ ) ],1,0.203252,98.983740
298,[ ( b -> B*~0 -> B~0 ) -> pi+ pi- ( D+ -> K(1)(1400)~0 -> pi+ ) ],1,0.203252,99.186992
299,[ ( b -> B*~0 -> B~0 ) -> pi+ pi- ( D+ -> K*(892)+ -> pi+ ) ],1,0.203252,99.390244
300,[ ( b -> B*~0 -> B~0 ) -> pi+ pi- ( D+ -> a(1)(1260)+ -> rho(770)+ -> pi+ ) ],1,0.203252,99.593496
301,[ ( b -> B- ) -> ( D*(2010)+ -> pi+ ) ( rho(770)- -> pi- ) ( D*(2010)+ -> D0 -> pi+ ) ],1,0.203252,99.796748
302,[ b~ -> ( B0 -> pi- ) ( B0 -> pi+ ) ( B0 -> D- -> pi- ) ],1,0.203252,100.000000

In [47]:
print(f"Categorie 17: {categories4.categories_map[17]}")
df = load_data(17)
g = mygroupby(df[['decay']], 'decay')
g

Categorie 17: Xc_signal_Ypis_diffVertex_SomeFromPV

,decay,count,Percentage,cumulative %
0,[ b -> pi+ [ ( B*- -> B- -> D0 ) -> pi- pi+ ] ],2,1.025641,1.025641
1,[ ( b~ -> B(2)*(5747)0 ) -> pi- [ ( B*+ -> B+ -> D~0 ) -> pi+ pi- ] ],2,1.025641,2.051282
2,[ ( b -> -10511.0 ) -> [ ( B- -> D*(2007)0 -> D0 ) -> pi+ pi- ] pi+ ],1,0.512821,2.564103
3,[ b~ -> ( B*0 -> B0 -> D(2)*(2460)- -> pi- ) ( Delta(1232)++ -> pi+ ) ( B*0 -> B0 -> D(2)*(2460)- -> D~0 -> pi- ) ],1,0.512821,3.076923
4,[ b~ -> ( B*0 -> B0 -> D*(2010)- -> pi- ) ( Sigma(1385)~+ -> pi+ ) ( B*0 -> B0 -> D*(2010)- -> D~0 -> pi- ) ],1,0.512821,3.589744
5,[ b~ -> ( B*0 -> B0 -> D- -> pi- ) ( Delta(1232)~0 -> pi+ ) ( B*0 -> B0 -> D- -> pi- ) ],1,0.512821,4.102564
6,[ b~ -> ( B*0 -> B0 -> D- -> pi- ) ( K~0 -> K(S)0 -> pi+ ) ( B*0 -> B0 -> D- -> pi- ) ],1,0.512821,4.615385
7,[ b~ -> ( B*0 -> B0 -> D- -> pi- ) ( eta -> pi+ ) ( B*0 -> B0 -> D- -> pi- ) ],1,0.512821,5.128205
8,[ b~ -> ( B*0 -> B0 -> D- -> pi- ) ( rho(770)+ -> pi+ ) ( B*0 -> B0 -> D- -> pi- ) ],1,0.512821,5.641026
9,[ b~ -> ( B*0 -> B0 -> D- -> pi- ) pi+ ( B*0 -> B0 -> D- -> pi- ) ],1,0.512821,6.153846
10,[ b~ -> ( B0 -> D*(2010)- -> D~0 -> pi- ) ( rho(770)+ -> pi+ ) ( B0 -> D*(2010)- -> pi- ) ],1,0.512821,6.666667
11,[ b~ -> ( K(1)(1270)+ -> pi- ) [ ( B(s)*0 -> B(s)0 -> D(s)*- -> D(s)- ) -> ( eta -> pi+ ) ( rho(770)- -> pi- ) ] ],1,0.512821,7.179487
12,[ b~ -> ( K*(892)+ -> pi+ ) [ ( B(s)0 -> D(s)+ ) -> ( eta'(958) -> eta -> pi- ) ( rho(770)+ -> pi+ ) ] ],1,0.512821,7.692308
13,[ b~ -> ( B(s)0 -> pi- ) [ ( K0 -> K(S)0 ) -> pi+ pi- ] ],1,0.512821,8.205128
14,[ b~ -> ( K*(892)+ -> pi+ ) [ ( B(s)0 -> D(s)+ -> eta'(958) -> eta ) -> pi- pi+ ] ],1,0.512821,8.717949
15,[ b~ -> ( K*(892)- -> K~0 -> K(S)0 -> pi+ ) [ ( B(s)*0 -> B(s)0 -> D(s)*+ -> D(s)+ -> phi(1020) -> eta ) -> pi- pi+ ] ],1,0.512821,9.230769
16,[ b~ -> ( K*(892)0 -> K0 -> K(S)0 -> pi- ) [ ( B(s)*0 -> B(s)0 -> D- -> a(1)(1260)- -> rho(770)0 ) -> pi+ pi- ] ],1,0.512821,9.743590
17,[ b~ -> ( K0 -> K(S)0 -> pi+ ) [ ( B(s)*0 -> B(s)0 -> D*(2010)+ -> D0 ) -> ( K(1)(1270)- -> rho(770)- -> pi- ) pi+ ] ],1,0.512821,10.256410
18,[ b~ -> ( K~0 -> K(S)0 -> pi- ) [ ( B*+ -> B+ -> D*(2007)~0 -> D~0 ) -> pi+ ( K*(892)0 -> pi- ) ] ],1,0.512821,10.769231
19,[ b~ -> ( Sigma(1385)~- -> pi- ) [ ( B*+ -> B+ -> D*(2007)~0 -> D~0 ) -> pi+ pi- ] ],1,0.512821,11.282051
20,[ b~ -> ( b(1)(1235)+ -> omega(782) -> pi- ) [ ( B*0 -> B0 -> D*(2010)- -> D~0 ) -> ( rho(770)+ -> pi+ ) pi- ] ],1,0.512821,11.794872
21,[ b~ -> ( b(1)(1235)- -> pi- ) [ ( B*0 -> B0 -> D*(2010)- ) -> ( D~0 -> K*(892)0 -> K+ ) pi- ] ],1,0.512821,12.307692
22,[ b~ -> ( eta -> gamma -> e- ) [ ( B*+ -> B+ -> D*(2007)~0 -> D~0 ) -> pi+ pi- ] ],1,0.512821,12.820513
23,[ b~ -> ( eta -> pi- ) [ ( B*+ -> B+ -> D~0 ) -> pi+ pi- ] ],1,0.512821,13.333333
24,[ b~ -> ( B*+ -> B+ -> D*(2007)~0 -> D~0 -> K(1)(1270)+ -> omega(782) -> pi- ) pi+ ( B*+ -> B+ -> D*(2007)~0 -> D~0 -> pi- ) ],1,0.512821,13.846154
...,...,...,...,...
168,[ b -> [ ( B(s)*~0 -> B(s)~0 ) -> K- ( D~0 -> pi+ ) ] ( K(2)*(1430)- -> K*(892)- -> K~0 -> K(S)0 -> pi- ) ],1,0.512821,87.692308
169,[ b -> K+ [ ( B*- -> B- -> D0 ) -> pi- pi+ ] ],1,0.512821,88.205128
170,[ b -> ( Delta(1232)+ -> pi+ ) [ ( B*~0 -> B~0 -> D+ -> omega(782) ) -> pi- pi+ ] ],1,0.512821,88.717949
171,[ b -> ( Sigma(1385)+ -> Sigma+ -> pi+ ) [ ( B(s)*~0 -> B(s)~0 ) -> ( omega(782) -> pi- ) pi+ ] ],1,0.512821,89.230769
172,[ b -> ( K(1)(1270)- -> pi+ ) [ ( B- -> D*(2007)0 -> D0 ) -> pi- ( K*(892)~0 -> pi+ ) ] ],1,0.512821,89.743590
173,[ b -> ( K*(892)+ -> K0 -> K(S)0 -> pi+ ) [ ( B*~0 -> B~0 -> D(2)*(2460)+ -> D+ ) -> pi- pi+ ] ],1,0.512821,90.256410
174,[ b -> ( K*(892)+ -> pi+ ) [ ( B*- -> B- -> D(1)(2420)0 -> D*(2007)0 -> D0 ) -> pi- pi+ ] ],1,0.512821,90.769231
175,[ b -> ( K*(892)+ -> pi+ ) [ ( B- -> D*(2007)0 -> D0 ) -> ( rho(770)- -> pi- ) pi+ ] ],1,0.512821,91.282051
176,[ b -> ( K*(892)+ -> pi+ ) [ ( B- -> D*(2007)0 -> D0 ) -> pi- pi+ ] ],1,0.512821,91.794872
177,[ b -> ( K*(892)~0 -> K- ) [ ( B(s)*~0 -> B(s)~0 -> D(s)*- -> D(s)- ) -> ( eta'(958) -> rho(770)0 -> pi+ ) ( rho(770)- -> pi- ) ] ],1,0.512821,92.307692
178,[ b -> ( K0 -> K(S)0 -> pi+ ) [ ( -20513.0 -> B*- -> B- -> D*(2007)0 -> D0 -> rho(770)0 ) -> pi- pi+ ] ],1,0.512821,92.820513
179,[ b -> ( Lambda -> p ) [ ( B(s)*~0 -> B(s)~0 -> D(s)+ ) -> ( eta'(958) -> eta -> pi- ) ( rho(770)+ -> pi+ ) ] ],1,0.512821,93.333333
180,[ b -> ( Lambda~ -> pi+ ) [ ( B*- -> B- -> D*(2007)0 -> D0 ) -> pi- pi+ ] ],1,0.512821,93.846154
181,[ b -> ( Sigma(1385)~0 -> Sigma~+ -> pi+ ) ( Sigma(1385)- -> pi- ) ( B(s)*~0 -> B(s)~0 -> rho(770)+ -> pi+ ) ],1,0.512821,94.358974
182,[ b -> ( rho(770)0 -> pi+ ) [ ( B*- -> B- -> D*(2007)0 -> D0 ) -> pi- mu+ ] ],1,0.512821,94.871795
183,[ b -> ( Sigma(b)*+ -> Lambda(b)0 -> Lambda(c)+ -> pi+ ) ( a(2)(1320)- -> rho(770)0 -> pi- ) ( Sigma(b)*+ -> Lambda(b)0 -> Lambda(c)+ -> pi+ ) ],1,0.512821,95.384615
184,[ b -> ( a(1)(1260)+ -> rho(770)0 -> pi+ ) [ ( B- -> D+ ) -> pi- pi+ ] ],1,0.512821,95.897436
185,[ b -> ( a(2)(1320)+ -> rho(770)+ -> pi+ ) [ ( B*- -> B- -> D0 ) -> pi- pi+ ] ],1,0.512821,96.410256
186,[ b -> ( eta -> pi+ ) [ ( B(s)~0 -> tau+ ) -> pi- pi+ ] ],1,0.512821,96.923077
187,[ b -> ( omega(782) -> pi+ ) [ ( -20523.0 -> B*~0 -> B~0 -> D+ ) -> ( omega(782) -> pi- ) pi+ ] ],1,0.512821,97.435897
188,[ b -> ( omega(782) -> pi+ ) [ ( B~0 -> D*(2010)+ ) -> ( D0 -> pi- ) pi+ ] ],1,0.512821,97.948718
189,[ b -> ( rho(770)+ -> pi+ ) [ ( -10523.0 -> B*- -> B- -> D0 ) -> ( K*(892)- -> pi- ) mu+ ] ],1,0.512821,98.461538
190,[ b -> ( rho(770)- -> pi- ) [ ( B*~0 -> B~0 -> D*(2010)- -> D~0 ) -> ( K*(892)+ -> pi+ ) ( rho(770)- -> pi- ) ] ],1,0.512821,98.974359
191,[ b -> ( rho(770)- -> pi- ) [ ( B*~0 -> B~0 -> D- ) -> pi+ pi- ] ],1,0.512821,99.487179
192,[ c -> [ ( B+ -> D~0 ) -> pi- pi+ ] ( f(2)(1270) -> pi- ) ],1,0.512821,100.000000